### ISSUE TITLE
Redux

### ISSUE THREAD

**Issue by senssei** [meetjspl/lodz#1]
Chciałbym chwilę opowiedzieć o architekturze Redux i języku Elm. 

Wszelki input mile widziany :smile:

**Comment by mostr** [comment]
W jednym talku redux i Elm? Może to rozdzielić i pokazać Elm architecture trochę bardziej szczegółowo, bo to fajna rzecz jest?

**Comment by senssei** [comment]
Dzięki za feedback. To dość duży orzech do zgryzienia na jedną sesję. :)

**Comment by adamniedzielski** [comment]
Ja chętnie posłucham o jednym i o drugim, ale może rzeczywiście lepiej wyjdzie to osobno?

**Comment by senssei** [comment]
Dobry feedback, trzeba to podzielić.
