### ISSUE TITLE
Promoting best practices by linting code

### ISSUE THREAD

**Issue by bardzusny** [meetjspl/lodz#17]
Code linting is one of the least talked about, but most useful tools in a front-end developer’s toolbox. It's the easiest thing we can do to significantly improve our code quality.

Most front-end applications already include basic JavaScript linter setup. But it’s often forgotten how easy and quick it is to go much farther, and ensure extensive static code analysis in your project, flavoured to fit with framework of your choice. Let’s talk about state-of-art solutions that can be used today in any project and greatly enhance your development workflow.

* Benefits of code linting that should become standard knowledge: typo protection, guarding against rookie mistakes/clear bad practices, “*junior-proofing*” of the codebase (haha!), … .
* Many often irritating things that simply go out of the window if we take small time investment to properly set-up appropriate linters.
* Comparison with application tests: how linters are basically simple tests that we get for free, and should be treated as so.
* Important part that they can play in both documenting **and** enforcing agreed code conventions.
* Outline of most common code linters: with main focus on JavaScript (ESLint, JSHint, ...) and languages compiled to it (i.e. TSLint for TypeScript). Short note on chosen style, template linters.
* Development flow/CI environment integrations: basic NPM scripts, how to launch them as part of application tests. Code editors integrations and linting code within your pre-commit/pre-push Git hooks (*Including obligatory screenshot of an actual CI build failing due to missing trailing comma/similar offence.* 😃 )

**Format**: 20-30min., slides + possible live demo of how linters can fit within real development workflow.

**Comment by senssei** [comment]
@bardzusny Super pomysł. Prezentacje czysto techniczna czy bardziej use-case i będziecie też o *netguru* troszkę opowiadać ? 

Jeśli Wasz HR jest zainteresowany sponsorowaniem eventu to zapraszamy do kontaktu. Bo jeśli tak, to chętnie zapraszamy do Łodzi wszystkich głosujących z Olsztyna i Gdańska. :)

**Comment by bardzusny** [comment]
Cześć @senssei - zrobił się z tego nieco niezamierzony wewnętrzny viral 😃. Przedstawię się jako pracownik Netguru (bo tak jest) - nic więcej nie jest pod tym kątem planowane. 🙂 Otrzymałem kilka zapytań o możliwość zobaczenia nagranych prezentacji, mam nadzieję że będą dostępne online.

**Comment by senssei** [comment]
Pytałem bardziej pod kątem zorganizowania eventu z Twoją prelekcją i pełnym brandingiem **Netguru** w roli sponsora. Dlaczego nie połączyć przyjemnego z pożytecznym. 

Jeśli jesteś zainteresowani czekamy na kontakt - np rafal.warzycha [at] gmail.com .  Dzięki temu będzie można znaleźć większe venue i nagłośnienie.

Dzięki temu można było ściągnąć jeszcze kogoś w Waw.  Jeśli miałbyś pomysł czyją prezentację warto tematycznie podłączyć pod Twoją daj znać. :) 

Prezentacje są od niedawna nagrywane. https://www.youtube.com/channel/UCHNR-FKCCkE7nvLpjV9t2qQ

**Comment by senssei** [comment]
@bardzusny BTW masz swoim portfolio prezentacje *bardziej* `node`-ową? Chętnie bym posłuchał o tym, bo wiem, że masz spore doświadczenie.

**Comment by senssei** [comment]
@bardzusny Będziesz też mówił o https://github.com/w0rp/ale ?

**Comment by bardzusny** [comment]
Temat potencjalnego zaangażowania Netguru w organizację przyszłych eventów przeniosłem na maila - włączając kogo trzeba w wątek. Ten issue chciałbym dalej traktować jako indywidualne zgłoszenie na meet-up w tym miesiącu - szczególnie dlatego, że to dla mnie ostatnia okazja do wygłoszenia talka przed wyprowadzką z Łodzi i dłuższym wyjazdem za granicę. 😄 

>Bo gdy zainteresowanie na GH przełoży się na to ilość RSVP pewno się nie zmieścimy w **6. Dzielnicy**.

Mamy kilku developerów w Łodzi, potencjalnie pojawiłby się zapewne ktoś z Warszawy - ale mowa wciąż o kilku osobach od nas które pojawiłyby się osobiście. Tłumem z tego źródła bym się nie martwił, szczególnie że mówimy o wtorku. 😃

>@bardzusny BTW masz swoim portfolio prezentacje *bardziej* `node`-ową? Chętnie bym posłuchał o tym, bo wiem, że masz spore doświadczenie.

Prawdę mówiąc nie - od dłuższego czasu jestem zaangażowany prawie wyłącznie w FE development. Za to temat lintowania kodu JavaScript jak najbardziej aplikuje się również do projektów Node'owych, i myślę że warto byłoby o tym wspomnieć - dzięki za zwrócenie na to uwagi. 👍 

>@bardzusny Będziesz też mówił o https://github.com/w0rp/ale ?

Integracja z edytorami tekstu jest wśród tematów do poruszenia, i na pewno pojawiłby się poświęcony im slajd, włącznie z listą najpopularnieszych rozwiązań. _ALE_ z pewnością byłby wśród nich - szczególnie że sam korzystam z niego na co dzień (jako wieloletni VIM-owiec). 😅

**Comment by senssei** [comment]
Twoja prezentacja została wybrana jako trzecia na #20 meet.js. 

Będziemy potrzebowali 2-3 zdania bio o Tobie, żeby umieścić je na meetup.

**Comment by bardzusny** [comment]
Super! 😄 Wysłałem wszystko w wiadomości mailowej. 🙂
