### ISSUE TITLE
GraphQL vs REST

### ISSUE THREAD

**Issue by AdamZaczek** [meetjspl/lodz#18]
Wprowadzenie do GraphQL jako innowacji w sposobie myślenia o danych. Porównanie GraphQL ze standardową architekturą REST oraz prezentacją omawianych konceptów na przykładzie, na jaki trafiliśmy w Netguru podczas pracy nad naszą nową aplikacją.

**Comment by senssei** [comment]
@AdamZaczek  - gratulacje, zapraszamy we wtorek. Potrzebujemy 2-3 zdania bio o Tobie.

**Comment by AdamZaczek** [comment]
Hej, super! To są zdania: Adam jest front-end developerem który równie dużo
czasu czasu spędza na czytaniu artykułów naukowych co na jeżdżeniu na
deskorolce. Kiedyś czuł że oczy mu krwawią gdy widział kod napisany w
Javascripcie, teraz tylko w tym chce programować. Nieoficjalnie pobił
rekord świata na deskorolce a teraz jest w trakcie oficjalnego ustanawiania
rekordu.

2017-06-12 8:21 GMT+02:00 Rafał Warzycha <notifications@github.com>:
