### ISSUE TITLE
Intro do CSS Grid

### ISSUE THREAD

**Issue by patryknawolski** [meetjspl/lodz#19]
CSS przez wiele lat nie udostępniał łatwego i niezawodnego narzędzia do umieszczania elementów na siatce, czyli tzw. gridzie. Dotychczas do tworzenia gridów korzystano z przeróżnych metod i hacków, z których każda miała pewne wady. Wynika to z faktu, że narzędzia takie jak `display: table`, `float` czy `display: inline-block` nie zostały stworzone z zamiarem bycia narzędziami do kreowania gridu.

Przez ostatni okres dzięki wzrastającemu supportowi przeglądarek swoją popularność zyskał Flexbox, który umilił codziennie życie niemałej ilości developerów. Krokiem w przód jest kolejna, relatywnie nowa właściwość **CSS Grid**, do której chciałbym was wprowadzić.

**CSS Grid** służy do budowania **dwu**wymiarowych layoutów, w przeciwieństwie do Flexboxa, który obsługuje **jedno**wymiarowe, podobnie zaś jak Flexbox pozwala on na rozkładanie elementów niezależnie od ich kolejności w kodzie HTML. Z pewnością znajduje się w czołówce najpotężniejszych narzędzi CSS i jest pierwszym w historii CSS natywnym rozwiązaniem do budowania gridów.

**Comment by senssei** [comment]
@patryknawolski  - gratulacje, zapraszamy we wtorek. Potrzebujemy 2-3 zdania bio o Tobie.
