### ISSUE TITLE
Make your PWA on iOS feel like native 

### ISSUE THREAD

**Issue by macap** [meetjspl/lodz#23]
Progressive Web Application is a wonderful technology which could ditch the need of creating native mobile applications, at the same providing better UX and improving conversions in your product. Everything works smoothly on Android, but what about iOS? Is is possible to create a functional PWA also on Apple’s mobile devices?

What will you learn:
- What is a current state of PWA support on iOS
- How popular PWAs behave on iOS devices
- How can you make your PWA better on iOS (handy workarounds for unsupported features)

Talk based on my surprisingly popular article [_Few Tips That Will Make Your PWA on iOS Feel Like Native_](https://www.netguru.co/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native)

**Comment by leszczynski-it** [comment]
@macap Will You be able to give presentation on 3rd october?

**Comment by macap** [comment]
@leszczynski-it 
Yup 👍
