### ISSUE TITLE
How to improve your web application? - Best Progressive Web Apps cases

### ISSUE THREAD

**Issue by krystiankoper** [meetjspl/lodz#24]
Have you ever wondered if some applications can be even faster? Sometimes it's not even very time-consuming to improve your application performance.
I'll try to show you possible improvements to web applications using some libraries focusing on PWA features (but not only). I like case studies because you don't need to reinvent the wheel so I'll base on some real examples of known applications such as:
- Tinder
- Pinterest
- Twitter

**Comment by leszczynski-it** [comment]
@krystiankoper Will You be able to give presentation on next meet.js, on 3rd october?
