### ISSUE TITLE
Are you confident it works? - E2E Testing with Cypress

### ISSUE THREAD

**Issue by vivensio** [meetjspl/lodz#25]
Hi!

I recently presented this talk at our internal conference - _Netguru Tech Talks_ and I think it would be awesome to talk about this with a broader audience.

Subject:
In this presentation, I talk about how we can improve our confidence in our code and our software by including end-to-end(E2E) tests in our workflow.

Thanks to **Cypress.js**, E2E testing is finally ready to come out of shadows. I'll go over the need of E2E tests, explain why I think Cypress has potential to **change the world** of E2E testing and how **fun** it is to **write E2E tests** using this library!

**Comment by leszczynski-it** [comment]
Hi @vivensio Will You be able to give presentation on wednesday on our meet.js?

Best Regards,
Piotr Leszczyński

**Comment by vivensio** [comment]
Hiya @leszczynski-it Thanks for considering this talk. Yes, I can do it on Wednesday. :)

**Comment by leszczynski-it** [comment]
@vivensio So I'll add You for presentation to agenda on 3rd October. We starting at 6:00 pm.
Can You send me couple word about You and description for presentation?

**Comment by vivensio** [comment]
@leszczynski-it Yeah sure, Is it possible to get your email address where I could send all the details?

**Comment by BTMPL** [comment]
@vivensio you can send in the details to baphemot@gmail.com ; generally we can use the sales pitch from the initial post to prepare a post for the social media but if you have something else in mind, let me know

**Comment by vivensio** [comment]
@BTMPL Done :)

**Comment by BTMPL** [comment]
![image](https://user-images.githubusercontent.com/247153/46332994-e3533600-c61e-11e8-9ac9-0a368e81eeda.png)
