### ISSUE TITLE
Write once, run anywhere - how does React XP manage to unify mobile and web development?

### ISSUE THREAD

**Issue by kernelgonnapanic** [meetjspl/lodz#26]
Hej,
Miałam okazję opowiedzieć trochę o React XP w tym roku na Meet.js Summit. Wydaje mi się, że temat jeszcze mało znany, może bylibyście zainteresowani moją prezentacją?

Temat: Write once, run anywhere - how does React XP manage to unify mobile and web development?

If the concept of running one piece of code on your iPhone, Android and as a web app excites you, I think you might want to hear this talk. 

We will be talking about how the multi-platform development looks in reality. I’ll tell you about the tools and techniques that we use to create apps for iOS, Android and web from one codebase. But at the same time I am going to share with you all the problems we’ve encountered and what we should have known when we started this journey. Is being JavaScript-speaking enough to build mobile apps? What can go wrong? Is it worth the fight? Let’s find out!

**Comment by BTMPL** [comment]
Hej @kernelgonnapanic - z uwagi na sezon grypowo-przeziębieniowy zwolnił nam się slot na środowy meet.js ; czy była by możliwość gościć cię na nim, czy trochę zbyt krótki termin?

**Comment by kernelgonnapanic** [comment]
Z tego co wiem to jeden ze slotów jest już przeznaczony dla mnie ;)

**Comment by BTMPL** [comment]
A widzisz, to i ja jestem zakręcony. Nie było tematu ;)
