### ISSUE TITLE
Flux architecture

### ISSUE THREAD

**Issue by bartekwitczak** [meetjspl/lodz#3]
Ogólny koncept, zalety i wady stosowania, kiedy warto, małe kodowanko na żywo ;) Przedstawione w kontekście React'a. Wszystko w kontekście Flux'a bez pochodnych Redux'ów, Kaflux'ów i innych.

**Comment by mostr** [comment]
@bartekwitczak to co, wbijać cię z tym na 17.05?

**Comment by bartekwitczak** [comment]
pewnie :)

**Comment by mostr** [comment]
Super, zarzucisz jeszcze jakiś krótki abstract do dodania na stronkę wydarzenia + parę słów o sobie dla lansu? :)

**Comment by mostr** [comment]
@bartekwitczak ping, podrzucisz dane do lansu?

**Comment by bartekwitczak** [comment]
Wieczorem podrzuce info

**Comment by bartekwitczak** [comment]
Wszyscy wiemy jak wygląda świat JS - codziennie nowe biblioteki, nowe zabawki, nowe forki tych samych rozwiązań ze zmiany w kolejności argumentów w funkcjach. Jednym słowem: dużo nowych rzeczy, a mało zmian. Na początku wydawało mi się, że React i Flux będą kolejnymi zabawkami w piaskownicy, z których nic nie wyjdzie. Podchodziłem do tematu trochę sceptycznie. 
Jednak po bliższym poznaniu, okazało się, że dzieje się coś naprawdę fajnego. 

Podczas prezentacji przedstawię architekturę FLUX w połączeniu z React. Będzie trochę prezentacji, w której przedsawię koncept, opiszę poszczególne elementy architektury. Następnie będzie trochę kodowania na żywo, gdzie pokażę w kodziku jak połączyć wszystko w jedną całość :)

Parę słów o mnie: aktualnie pracuję jako developer w firmie TomTom, wcześniej pracowałem zarówno w startupie, średniej i dużej firmie. Na co dzień pracuję jako fullstack developer - JS + JVM. Codziennie staram się uczyć nowych rzeczy :)

Takie coś wystarczy?

**Comment by mostr** [comment]
Pewnie, wieczorem wrzucę aktualizację

2016-04-29 15:03 GMT+02:00 Bartlomiej Witczak <notifications@github.com>:

> Wszyscy wiemy jak wygląda świat JS - codziennie nowe biblioteki, nowe
> zabawki, nowe forki tych samych rozwiązań ze zmiany w kolejności argumentów
> w funkcjach. Jednym słowem: dużo nowych rzeczy, a mało zmian. Na początku
> wydawało mi się, że React i Flux będą kolejnymi zabawkami w piaskownicy, z
> których nic nie wyjdzie. Podchodziłem do tematu trochę sceptycznie.
> Jednak po bliższym poznaniu, okazało się, że dzieje się coś naprawdę
> fajnego.
>
> Podczas prezentacji przedstawię architekturę FLUX w połączeniu z React.
> Będzie trochę prezentacji, w której przedsawię koncept, opiszę poszczególne
> elementy architektury. Następnie będzie trochę kodowania na żywo, gdzie
> pokażę w kodziku jak połączyć wszystko w jedną całość :)
>
> Parę słów o mnie: aktualnie pracuję jako developer w firmie TomTom,
> wcześniej pracowałem zarówno w startupie, średniej i dużej firmie. Na co
> dzień pracuję jako fullstack developer - JS + JVM. Codziennie staram się
> uczyć nowych rzeczy :)
>
> Takie coś wystarczy?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/meetjspl/lodz/issues/3#issuecomment-215705473>
>



-- 
Michał Ostruszka
http://michalostruszka.pl

**Comment by mostr** [comment]
Dzięki za talka! Zamykam
