### ISSUE TITLE
ng-upgrade

### ISSUE THREAD

**Issue by leszczynski-it** [meetjspl/lodz#5]
Historia dodania do istniejącej aplikacji w Angularze 1.3, Angulara 2.0 i na jakie przygody trafiłem po drodze.

**Comment by mostr** [comment]
Chcesz to zrobić teraz, 17-go?

**Comment by leszczynski-it** [comment]
Jasne, bardzo chętnie :)

**Comment by mostr** [comment]
Gitara, to poproszę o parę słów ładnego abstractu i tytuł + 2 zdania o sobie dla lansu :)

**Comment by leszczynski-it** [comment]
Podeślę w weekend, ok?

**Comment by mostr** [comment]
@leszczynski-it ping :) Chciałbym wrzucić temat w agendę

**Comment by leszczynski-it** [comment]
ng-forward – Piotr Leszczyński 
2 lata temu team angulara oznajmił, że pracują nad drugą wersją Angulara, która wspólnego z ówczesnymi wersjami Angulara niewiele będzie miała wspólnego. Po 2 latach, Angular 2 wszedł w fazę RC. W prezentacji przedstawię proces migracji z Angulara 1 do Angulara 2, oraz jakie decyzje po drodze musiałem podjąć. Postaram się również przedstawić podstawowe różnice między nimi, oraz jaką pomoc w migracji dostajemy od twórów Angulara, w postaci ng-forward.  
Pracuje w firmie GFT jako JavaScript Developer z aplikacjami tworzonymi w Angularze. Współtworzę Just4Fun Podcast. W wolnym czasie staram się sprostać trudniej sztuce, bycia z front-endem na bieżąco.

**Comment by leszczynski-it** [comment]
@mostr mogę Ci prosić o poprawienie opisu? :) Oczywiście powinno być "w postaci ng-upgrade", a nie ng-forward :)

**Comment by mostr** [comment]
Zrobione, chyba wszędzie. Jak jeszcze gdzieś znajdziesz - krzycz!

**Comment by leszczynski-it** [comment]
https://www.facebook.com/events/926104037488046/permalink/933384160093367/
Tutaj w poście jeszcze zostało, da się poprawić?

**Comment by mostr** [comment]
O widzisz - poprawione.

On Tue, May 10, 2016 at 9:41 AM, Piotr Leszczyński <notifications@github.com
> wrote:

> https://www.facebook.com/events/926104037488046/permalink/933384160093367/
> Tutaj w poście jeszcze zostało, da się poprawić?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/meetjspl/lodz/issues/5#issuecomment-218081946>
>



-- 
Michał Ostruszka
http://michalostruszka.pl

**Comment by mostr** [comment]
Dzięki za talka! Zamykam
